FROM node:18.10.0-alpine

# Install curl
RUN apk add --no-cache curl

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm install

RUN npm run build

# Expose the port that Vite uses
EXPOSE 4173

EXPOSE 5173

# Start the app in production
CMD ["npm", "run", "dev"]

# Denne filen er for å bygge container-image til backend. Senere kan vi kjøre container-image ved bruk av docker. 
# Denne filen forklarer hvordan docker-imaget skal bli bygget. Container-teknologi er et isolert opertativsystem som 
# KUN kjører applikasjoner på pcen din lokalt i sitt operativsystem, uten å tilgang ut til resten av maskinen/operativsystemet. 