FROM node:alpine

# Install curl
RUN apk add --no-cache curl

WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Start your application
CMD ["npm", "run", "dev"]
